name: flamingo

channels:
  - pytorch
  - conda-forge

dependencies:
  - cpuonly
  - cluster_tools
  - scikit-image
  - pybdv
  - pytorch
  - s3fs
  - torch_em
  - trimesh
  - z5py
  # Don't install zarr v3, as we are not sure that it is compatible with MoBIE etc. yet
  - zarr <3
